In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
list_of_list=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(1,20) 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
np.arange(16) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones((2,5),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.zeros((12,15),int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [ ]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [ ]:
np.linspace(0,2)

array([0.        , 0.04081633, 0.08163265, 0.12244898, 0.16326531,
       0.20408163, 0.24489796, 0.28571429, 0.32653061, 0.36734694,
       0.40816327, 0.44897959, 0.48979592, 0.53061224, 0.57142857,
       0.6122449 , 0.65306122, 0.69387755, 0.73469388, 0.7755102 ,
       0.81632653, 0.85714286, 0.89795918, 0.93877551, 0.97959184,
       1.02040816, 1.06122449, 1.10204082, 1.14285714, 1.18367347,
       1.2244898 , 1.26530612, 1.30612245, 1.34693878, 1.3877551 ,
       1.42857143, 1.46938776, 1.51020408, 1.55102041, 1.59183673,
       1.63265306, 1.67346939, 1.71428571, 1.75510204, 1.79591837,
       1.83673469, 1.87755102, 1.91836735, 1.95918367, 2.        ])

In [ ]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(3,5)

array([[0.92396559, 0.3627637 , 0.0458656 , 0.38107679, 0.60278116],
       [0.27069825, 0.54863744, 0.73549041, 0.50384367, 0.81506323],
       [0.25354497, 0.34206481, 0.35196673, 0.94910015, 0.34480589]])

In [ ]:
 np.random.randn(3,5)

array([[-2.22521252,  1.50620294,  0.89574405, -0.28152553,  0.21520973],
       [ 1.31861621,  0.17025344,  1.51846917,  0.02117315,  1.02618993],
       [-0.30945301,  1.39811269,  0.6397809 , -0.33065021, -0.40766878]])

In [ ]:
np.random.randint(34,99)

81

In [ ]:
np.random.randint(34,99)

88

In [ ]:
np.random.randint(34,49,100)

array([42, 46, 35, 44, 42, 47, 39, 48, 34, 35, 36, 45, 40, 48, 44, 42, 36,
       39, 37, 38, 42, 36, 40, 47, 36, 43, 40, 44, 48, 45, 37, 43, 44, 35,
       45, 40, 43, 44, 46, 36, 47, 47, 38, 46, 37, 44, 45, 36, 44, 48, 35,
       48, 36, 42, 45, 42, 41, 36, 47, 38, 47, 46, 37, 45, 38, 47, 46, 40,
       38, 47, 41, 47, 46, 42, 48, 47, 40, 39, 36, 39, 44, 47, 44, 42, 40,
       34, 45, 34, 46, 36, 47, 41, 35, 41, 40, 36, 40, 35, 37, 46],
      dtype=int32)

In [ ]:
sample_array=np.arange(100)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
rand_array=np.random.randint(0,100,20)
rand_array

array([90, 12, 57, 38, 41, 31, 58, 50, 48, 20,  7, 32,  2, 56, 65, 34, 25,
       40, 62, 38], dtype=int32)

In [ ]:
sample_array.reshape(2,5)

ValueError: cannot reshape array of size 100 into shape (2,5)

In [ ]:
sample_array.reshape(10,10)

In [ ]:
sample_array.reshape(20,5)

In [ ]:
sample_array.reshape(2,50)

In [ ]:
rand_array.min()

In [ ]:
rand_array.argmin()

In [ ]:
rand_array.max()

In [ ]:
rand_array.argmax()

In [ ]:
sample_array.dtype

In [ ]:
a=np.eye(5)
a

In [ ]:
a.T

In [ ]:
a=np.random.rand(2,3)
a

In [ ]:
 a.T

In [ ]:
sample_array=np .arange (10,22)
sample_array

In [ ]:
sample_array[-5]

sample_array[5]

In [ ]:
sample_array[3:7]

In [ ]:
sample_array[1:4]=100
sample_array

In [ ]:
sample_array=np.arange(10,21)
sample_array

In [ ]:
sample_array[2:6]

array([2, 3, 4, 5])

In [ ]:
subset_sample_array=sample_array[2:6]
subset_sample_array

array([2, 3, 4, 5])

In [ ]:
subset_sample_array[1:2]=501
subset_sample_array

array([  2, 501,   4,   5])

In [ ]:
subset_sample_array[:]=501
subset_sample_array

array([501, 501, 501, 501])

In [ ]:
Two-Dimensional array

In [ ]:
import numpy as v

In [ ]:
sample_matrix=v.array(([50,20,16,23],[55,14,5,26],[12,64,65,89]))
sample_matrix

array([[50, 20, 16, 23],
       [55, 14,  5, 26],
       [12, 64, 65, 89]])

In [ ]:
sample_matrix[2][3]

np.int64(89)

In [ ]:
sample_matrix[2][:]

array([12, 64, 65, 89])

In [ ]:
sample_matrix[:][1]

array([55, 14,  5, 26])

In [ ]:
sample_matrix

array([[50, 20, 16, 23],
       [55, 14,  5, 26],
       [12, 64, 65, 89]])

In [ ]:
sample_matrix[2]

array([12, 64, 65, 89])

In [ ]:
 sample_matrix[:,(1,3)]

array([[20, 23],
       [14, 26],
       [64, 89]])

In [ ]:
  sample_matrix[(1,2),:]

array([[55, 14,  5, 26],
       [12, 64, 65, 89]])

sample_matrix[(1)]=22,55,12,46

In [ ]:
sample_matrix

array([[50, 20, 16, 23],
       [55, 14,  5, 26],
       [12, 64, 65, 89]])

In [ ]:
sample_matrix[(1)]=22,55,12,46

In [ ]:
sample_matrix

array([[50, 20, 16, 23],
       [22, 55, 12, 46],
       [12, 64, 65, 89]])

In [ ]:
sample_matrix[(2)]=23,44,50,60

In [ ]:
sample_matrix

array([[50, 20, 16, 23],
       [22, 55, 12, 46],
       [23, 44, 50, 60]])

In [ ]:
Selection Techniques

In [ ]:
sample_array=v.arange(1,20)

In [ ]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [ ]:
sample_array-sample_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
sample_array*sample_array

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [ ]:
sample_array[(5)]=20

In [ ]:
sample_array

array([ 1,  2,  3,  4,  5, 20,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
sample_array[(5)]=6

In [ ]:
v.exp(sample_array) 

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [ ]:
v.exp(sample_array) # enponential

In [ ]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [ ]:
v.log(sample_array) #square root

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [ ]:
v.log(sample_array)  #logarithm

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [ ]:
v.min(sample_array)

np.int64(1)

In [ ]:
np.max(sample_array)

np.int64(19)

In [ ]:
np.argmin(sample_array) # index of min

np.int64(0)

In [ ]:
np.argmax(sample_array) # index of max

np.int64(18)

In [ ]:
v.square(sample_array) 

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [ ]:
v.std(sample_array) # standard deviation

np.float64(5.477225575051661)

In [ ]:
v.var(sample_array) 

np.float64(30.0)

In [ ]:
v.mean(sample_array)

np.float64(10.0)

In [ ]:
array=v.random.randn(2,3) # normal distribution for row and column
array

array([[ 0.94514062,  3.13873799, -0.13628702],
       [ 0.57254932,  0.22974568, -0.98304035]])

In [ ]:
v.round(array,decimals=1) # decimal ke baad kitne number chahiye

array([[ 0.9,  3.1, -0.1],
       [ 0.6,  0.2, -1. ]])

In [ ]:
sports=v.array(['cricket','kanche','football','guchikhel','diskpati'])
v.unique(sports)

array(['cricket', 'diskpati', 'football', 'guchikhel', 'kanche'],
      dtype='<U9')

In [ ]:
sports=v.array(['cricket','basketball','football','guchikhel','diskpati'])
v.unique(sports)

array(['basketball', 'cricket', 'diskpati', 'football', 'guchikhel'],
      dtype='<U10')